+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_ptlep_v1/unfold_96_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_ptlep_v1/unfold_outputfile96
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_ptlep_v1/unfold_errorfile96
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_ptlep_v1/unfold_myexe96.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
