+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out1/significance_53_condor.sh
arguments    = test_sig2
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out1/significance_outputfile53
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out1/significance_errorfile53
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out1/significance_myexe53.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
