+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_81_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_outputfile81
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_errorfile81
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_myexe81.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
