+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_jet1pt_v1/unfold_5_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_jet1pt_v1/unfold_outputfile5
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_jet1pt_v1/unfold_errorfile5
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_jet1pt_v1/unfold_myexe5.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
