+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_61_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_outputfile61
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_errorfile61
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_jet1pt_v1/unfold_myexe61.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
