+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_48_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_outputfile48
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_errorfile48
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_myexe48.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
