+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_77_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_outputfile77
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_errorfile77
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out2/fiducial_myexe77.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
