./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data data_lepton medium 4 10
./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data_fake data_lepton medium 4 10
./make_hist2 filelist_dir/tight_for_fakephoton_WGJets.txt $1 2018 mc all true WGJets medium 4 10
./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data data_lepton medium 4 7
./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data_fake data_lepton medium 4 7
./make_hist2 filelist_dir/tight_for_fakephoton_WGJets.txt $1 2018 mc all true WGJets medium 4 7
./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data data_lepton medium 7 10
./make_hist2 filelist_dir/tight_for_fakephoton_lepton.txt $1 2018 data all data_fake data_lepton medium 7 10
./make_hist2 filelist_dir/tight_for_fakephoton_WGJets.txt $1 2018 mc all true WGJets medium 7 10
