+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_jet1pt/unfold_82_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_jet1pt/unfold_outputfile82
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_jet1pt/unfold_errorfile82
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_jet1pt/unfold_myexe82.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
