#./test_histgram filelist_dir/tight_WGJets2.txt test_uncertainty_hist_v2 2018 electron mc signal WGJets medium
./test_histgram filelist_dir/tight_ST_s.txt test_uncertainty_hist_v2 2018 electron mc signal ST_s medium
./test_histgram filelist_dir/tight_ST_t.txt test_uncertainty_hist_v2 2018 electron mc signal ST_t medium
./test_histgram filelist_dir/tight_ST_tbar.txt test_uncertainty_hist_v2 2018 electron mc signal ST_tbar medium
./test_histgram filelist_dir/tight_ST_tW.txt test_uncertainty_hist_v2 2018 electron mc signal ST_tW medium
./test_histgram filelist_dir/tight_ST_tbarW.txt test_uncertainty_hist_v2 2018 electron mc signal ST_tbarW medium
./test_histgram filelist_dir/tight_TTG.txt test_uncertainty_hist_v2 2018 electron mc signal TTG medium
./test_histgram filelist_dir/tight_WGJJ2.txt test_uncertainty_hist_v2 2018 electron mc signal WGJJ medium
./test_histgram filelist_dir/tight_WW.txt test_uncertainty_hist_v2 2018 electron mc signal WW medium
./test_histgram filelist_dir/tight_WZ.txt test_uncertainty_hist_v2 2018 electron mc signal WZ medium
./test_histgram filelist_dir/tight_ZZ.txt test_uncertainty_hist_v2 2018 electron mc signal ZZ medium
./test_histgram filelist_dir/tight_ZG.txt test_uncertainty_hist_v2 2018 electron mc signal ZG medium
#./test_histgram filelist_dir/tight_WGJets2.txt test_uncertainty_hist_v2 2018 electron mc control WGJets medium
./test_histgram filelist_dir/tight_ST_s.txt test_uncertainty_hist_v2 2018 electron mc control ST_s medium
./test_histgram filelist_dir/tight_ST_t.txt test_uncertainty_hist_v2 2018 electron mc control ST_t medium
./test_histgram filelist_dir/tight_ST_tbar.txt test_uncertainty_hist_v2 2018 electron mc control ST_tbar medium
./test_histgram filelist_dir/tight_ST_tW.txt test_uncertainty_hist_v2 2018 electron mc control ST_tW medium
./test_histgram filelist_dir/tight_ST_tbarW.txt test_uncertainty_hist_v2 2018 electron mc control ST_tbarW medium
./test_histgram filelist_dir/tight_TTG.txt test_uncertainty_hist_v2 2018 electron mc control TTG medium
./test_histgram filelist_dir/tight_WGJJ2.txt test_uncertainty_hist_v2 2018 electron mc control WGJJ medium
./test_histgram filelist_dir/tight_WW.txt test_uncertainty_hist_v2 2018 electron mc control WW medium
./test_histgram filelist_dir/tight_WZ.txt test_uncertainty_hist_v2 2018 electron mc control WZ medium
./test_histgram filelist_dir/tight_ZZ.txt test_uncertainty_hist_v2 2018 electron mc control ZZ medium
./test_histgram filelist_dir/tight_ZG.txt test_uncertainty_hist_v2 2018 electron mc control ZG medium
./test_histgram filelist_dir/tight_electron.txt test_uncertainty_hist_v2 2018 electron fakephoton signal SingleElectron medium
./test_histgram filelist_dir/tight_electron.txt test_uncertainty_hist_v2 2018 electron fakephoton control SingleElectron medium
