./make_hist filelist_dir/tight_for_analysis_WGJets2.txt 1_out_mva_1 2018 all mc signal WGJets medium
./make_hist filelist_dir/tight_for_analysis_ST_s.txt 1_out_mva_1 2018 all mc signal ST_s medium
./make_hist filelist_dir/tight_for_analysis_ST_t.txt 1_out_mva_1 2018 all mc signal ST_t medium
./make_hist filelist_dir/tight_for_analysis_ST_tbar.txt 1_out_mva_1 2018 all mc signal ST_tbar medium
./make_hist filelist_dir/tight_for_analysis_ST_tW.txt 1_out_mva_1 2018 all mc signal ST_tW medium
./make_hist filelist_dir/tight_for_analysis_ST_tbarW.txt 1_out_mva_1 2018 all mc signal ST_tbarW medium
./make_hist filelist_dir/tight_for_analysis_WGJJ.txt 1_out_mva_1 2018 all mc signal WGJJ medium
./make_hist filelist_dir/tight_for_analysis_WW.txt 1_out_mva_1 2018 all mc signal WW medium
./make_hist filelist_dir/tight_for_analysis_WZ.txt 1_out_mva_1 2018 all mc signal WZ medium
./make_hist filelist_dir/tight_for_analysis_ZZ.txt 1_out_mva_1 2018 all mc signal ZZ medium
./make_hist filelist_dir/tight_for_analysis_ZG.txt 1_out_mva_1 2018 all mc signal ZG medium
./make_hist filelist_dir/tight_for_analysis_TTG.txt 1_out_mva_1 2018 all mc signal TTG medium
