./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJets_new.txt without_opt_ptlep10_mjj1d 2018 muon mc signal barrel WGJets medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJets_new.txt without_opt_ptlep10_mjj1d 2018 muon mc signal endcap WGJets medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJets_new.txt without_opt_ptlep10_mjj1d 2018 electron mc signal barrel WGJets medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJets_new.txt without_opt_ptlep10_mjj1d 2018 electron mc signal endcap WGJets medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJJ.txt without_opt_ptlep10_mjj1d 2018 muon mc signal barrel WGJJ medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJJ.txt without_opt_ptlep10_mjj1d 2018 muon mc signal endcap WGJJ medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJJ.txt without_opt_ptlep10_mjj1d 2018 electron mc signal barrel WGJJ medium
./make_hist_without_opt_and_ptlep10_mjj1d filelist_dir2/tight_for_analysis_WGJJ.txt without_opt_ptlep10_mjj1d 2018 electron mc signal endcap WGJJ medium
