+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_ptlep_v2/unfold_4_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_ptlep_v2/unfold_outputfile4
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_ptlep_v2/unfold_errorfile4
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_ptlep_v2/unfold_myexe4.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
