+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_photonet_v1/unfold_130_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_photonet_v1/unfold_outputfile130
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_photonet_v1/unfold_errorfile130
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step5_unfold/unfold_photonet_v1/unfold_myexe130.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
