+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out2/significance_32_condor.sh
arguments    = test_sig1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out2/significance_outputfile32
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out2/significance_errorfile32
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out2/significance_myexe32.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
