+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out2/aqgc_17_condor.sh
arguments    = test_aqgc1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out2/aqgc_outputfile17
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out2/aqgc_errorfile17
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out2/aqgc_myexe17.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
