./make_hist filelist_dir2/tight_for_analysis_electron.txt $1 2018 electron data aqgc all SingleElectron medium
./make_hist filelist_dir2/loose_for_analysis_electron.txt $1 2018 electron doublefake aqgc all SingleElectron medium
./make_hist filelist_dir2/tight_for_analysis_electron.txt $1 2018 electron fakephoton aqgc all SingleElectron medium
./make_hist filelist_dir2/loose_for_analysis_electron.txt $1 2018 electron fakelepton aqgc all SingleElectron medium
./make_hist filelist_dir2/tight_for_analysis_muon.txt $1 2018 muon data aqgc all SingleMuon medium
./make_hist filelist_dir2/loose_for_analysis_muon.txt $1 2018 muon doublefake aqgc all SingleMuon medium
./make_hist filelist_dir2/tight_for_analysis_muon.txt $1 2018 muon fakephoton aqgc all SingleMuon medium
./make_hist filelist_dir2/loose_for_analysis_muon.txt $1 2018 muon fakelepton aqgc all SingleMuon medium
./make_hist filelist_dir2/tight_for_analysis_WGJets_new.txt $1 2018 electron mc aqgc all WGJets medium
./make_hist filelist_dir2/tight_for_analysis_ST_s.txt $1 2018 electron mc aqgc all ST_s medium
./make_hist filelist_dir2/tight_for_analysis_ST_t.txt $1 2018 electron mc aqgc all ST_t medium
./make_hist filelist_dir2/tight_for_analysis_ST_tbar.txt $1 2018 electron mc aqgc all ST_tbar medium
./make_hist filelist_dir2/tight_for_analysis_ST_tW.txt $1 2018 electron mc aqgc all ST_tW medium
./make_hist filelist_dir2/tight_for_analysis_ST_tbarW.txt $1 2018 electron mc aqgc all ST_tbarW medium
./make_hist filelist_dir2/tight_for_analysis_WGJJ.txt $1 2018 electron mc aqgc all WGJJ medium
./make_hist filelist_dir2/tight_for_analysis_WW.txt $1 2018 electron mc aqgc all WW medium
./make_hist filelist_dir2/tight_for_analysis_WZ.txt $1 2018 electron mc aqgc all WZ medium
./make_hist filelist_dir2/tight_for_analysis_ZZ.txt $1 2018 electron mc aqgc all ZZ medium
./make_hist filelist_dir2/tight_for_analysis_ZG.txt $1 2018 electron mc aqgc all ZG medium
./make_hist filelist_dir2/tight_for_analysis_TTG.txt $1 2018 electron mc aqgc all TTG medium
./make_hist filelist_dir2/tight_for_analysis_WGJets_new.txt $1 2018 muon mc aqgc all WGJets medium
./make_hist filelist_dir2/tight_for_analysis_ST_s.txt $1 2018 muon mc aqgc all ST_s medium
./make_hist filelist_dir2/tight_for_analysis_ST_t.txt $1 2018 muon mc aqgc all ST_t medium
./make_hist filelist_dir2/tight_for_analysis_ST_tbar.txt $1 2018 muon mc aqgc all ST_tbar medium
./make_hist filelist_dir2/tight_for_analysis_ST_tW.txt $1 2018 muon mc aqgc all ST_tW medium
./make_hist filelist_dir2/tight_for_analysis_ST_tbarW.txt $1 2018 muon mc aqgc all ST_tbarW medium
./make_hist filelist_dir2/tight_for_analysis_WGJJ.txt $1 2018 muon mc aqgc all WGJJ medium
./make_hist filelist_dir2/tight_for_analysis_WW.txt $1 2018 muon mc aqgc all WW medium
./make_hist filelist_dir2/tight_for_analysis_WZ.txt $1 2018 muon mc aqgc all WZ medium
./make_hist filelist_dir2/tight_for_analysis_ZZ.txt $1 2018 muon mc aqgc all ZZ medium
./make_hist filelist_dir2/tight_for_analysis_ZG.txt $1 2018 muon mc aqgc all ZG medium
./make_hist filelist_dir2/tight_for_analysis_TTG.txt $1 2018 muon mc aqgc all TTG medium
