#signal
./make_hist_bkg filelist_dir/tight_for_analysis_electron.txt 1_out_2 2016 electron data signal SingleElectron medium
./make_hist_bkg filelist_dir/loose_for_analysis_electron.txt 1_out_2 2016 electron doublefake signal SingleElectron medium
./make_hist_bkg filelist_dir/tight_for_analysis_electron.txt 1_out_2 2016 electron fakephoton signal SingleElectron medium
./make_hist_bkg filelist_dir/loose_for_analysis_electron.txt 1_out_2 2016 electron fakelepton signal SingleElectron medium
#control
./make_hist_bkg filelist_dir/tight_for_analysis_electron.txt 1_out_2 2016 electron data control SingleElectron medium
./make_hist_bkg filelist_dir/loose_for_analysis_electron.txt 1_out_2 2016 electron doublefake control SingleElectron medium
./make_hist_bkg filelist_dir/tight_for_analysis_electron.txt 1_out_2 2016 electron fakephoton control SingleElectron medium
./make_hist_bkg filelist_dir/loose_for_analysis_electron.txt 1_out_2 2016 electron fakelepton control SingleElectron medium
#signal
./make_hist_bkg filelist_dir/tight_for_analysis_muon.txt 1_out_2 2016 muon data signal SingleMuon medium
./make_hist_bkg filelist_dir/loose_for_analysis_muon.txt 1_out_2 2016 muon doublefake signal SingleMuon medium
./make_hist_bkg filelist_dir/tight_for_analysis_muon.txt 1_out_2 2016 muon fakephoton signal SingleMuon medium
./make_hist_bkg filelist_dir/loose_for_analysis_muon.txt 1_out_2 2016 muon fakelepton signal SingleMuon medium
#control
./make_hist_bkg filelist_dir/tight_for_analysis_muon.txt 1_out_2 2016 muon data control SingleMuon medium
./make_hist_bkg filelist_dir/loose_for_analysis_muon.txt 1_out_2 2016 muon doublefake control SingleMuon medium
./make_hist_bkg filelist_dir/tight_for_analysis_muon.txt 1_out_2 2016 muon fakephoton control SingleMuon medium
./make_hist_bkg filelist_dir/loose_for_analysis_muon.txt 1_out_2 2016 muon fakelepton control SingleMuon medium
#electron
./make_hist_bkg filelist_dir/tight_for_analysis_WGJets2.txt 1_out_2 2016 muon mc signal WGJets medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_s.txt 1_out_2 2016 electron mc signal ST_s medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_t.txt 1_out_2 2016 electron mc signal ST_t medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbar.txt 1_out_2 2016 electron mc signal ST_tbar medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tW.txt 1_out_2 2016 electron mc signal ST_tW medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbarW.txt 1_out_2 2016 electron mc signal ST_tbarW medium
./make_hist_bkg filelist_dir/tight_for_analysis_TTG.txt 1_out_2 2016 electron mc signal TTG medium
#./make_hist_bkg filelist_dir/tight_for_analysis_WGJJ.txt 1_out_2 2016 electron mc signal WGJJ medium
./make_hist_bkg filelist_dir/tight_for_analysis_WW.txt 1_out_2 2016 electron mc signal WW medium
./make_hist_bkg filelist_dir/tight_for_analysis_WZ.txt 1_out_2 2016 electron mc signal WZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZZ.txt 1_out_2 2016 electron mc signal ZZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZG.txt 1_out_2 2016 electron mc signal ZG medium
./make_hist_bkg filelist_dir/tight_for_analysis_WGJets2.txt 1_out_2 2016 electron mc control WGJets medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_s.txt 1_out_2 2016 electron mc control ST_s medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_t.txt 1_out_2 2016 electron mc control ST_t medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbar.txt 1_out_2 2016 electron mc control ST_tbar medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tW.txt 1_out_2 2016 electron mc control ST_tW medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbarW.txt 1_out_2 2016 electron mc control ST_tbarW medium
./make_hist_bkg filelist_dir/tight_for_analysis_TTG.txt 1_out_2 2016 electron mc control TTG medium
#./make_hist_bkg filelist_dir/tight_for_analysis_WGJJ.txt 1_out_2 2016 electron mc control WGJJ medium
./make_hist_bkg filelist_dir/tight_for_analysis_WW.txt 1_out_2 2016 electron mc control WW medium
./make_hist_bkg filelist_dir/tight_for_analysis_WZ.txt 1_out_2 2016 electron mc control WZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZZ.txt 1_out_2 2016 electron mc control ZZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZG.txt 1_out_2 2016 electron mc control ZG medium
#muon
./make_hist_bkg filelist_dir/tight_for_analysis_WGJets2.txt 1_out_2 2016 muon mc signal WGJets medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_s.txt 1_out_2 2016 muon mc signal ST_s medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_t.txt 1_out_2 2016 muon mc signal ST_t medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbar.txt 1_out_2 2016 muon mc signal ST_tbar medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tW.txt 1_out_2 2016 muon mc signal ST_tW medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbarW.txt 1_out_2 2016 muon mc signal ST_tbarW medium
./make_hist_bkg filelist_dir/tight_for_analysis_TTG.txt 1_out_2 2016 muon mc signal TTG medium
#./make_hist_bkg filelist_dir/tight_for_analysis_WGJJ.txt 1_out_2 2016 muon mc signal WGJJ medium
./make_hist_bkg filelist_dir/tight_for_analysis_WW.txt 1_out_2 2016 muon mc signal WW medium
./make_hist_bkg filelist_dir/tight_for_analysis_WZ.txt 1_out_2 2016 muon mc signal WZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZZ.txt 1_out_2 2016 muon mc signal ZZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZG.txt 1_out_2 2016 muon mc signal ZG medium
./make_hist_bkg filelist_dir/tight_for_analysis_WGJets2.txt 1_out_2 2016 muon mc control WGJets medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_s.txt 1_out_2 2016 muon mc control ST_s medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_t.txt 1_out_2 2016 muon mc control ST_t medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbar.txt 1_out_2 2016 muon mc control ST_tbar medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tW.txt 1_out_2 2016 muon mc control ST_tW medium
./make_hist_bkg filelist_dir/tight_for_analysis_ST_tbarW.txt 1_out_2 2016 muon mc control ST_tbarW medium
./make_hist_bkg filelist_dir/tight_for_analysis_TTG.txt 1_out_2 2016 muon mc control TTG medium
#./make_hist_bkg filelist_dir/tight_for_analysis_WGJJ.txt 1_out_2 2016 muon mc control WGJJ medium
./make_hist_bkg filelist_dir/tight_for_analysis_WW.txt 1_out_2 2016 muon mc control WW medium
./make_hist_bkg filelist_dir/tight_for_analysis_WZ.txt 1_out_2 2016 muon mc control WZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZZ.txt 1_out_2 2016 muon mc control ZZ medium
./make_hist_bkg filelist_dir/tight_for_analysis_ZG.txt 1_out_2 2016 muon mc control ZG medium
