./make_hist_control filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 muon mc control barrel WGJets medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 muon mc control endcap WGJets medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 electron mc control barrel WGJets medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 electron mc control endcap WGJets medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 muon mc control barrel WGJJ medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 muon mc control endcap WGJJ medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 electron mc control barrel WGJJ medium
./make_hist_control filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 electron mc control endcap WGJJ medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 muon mc signal barrel WGJets medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 muon mc signal endcap WGJets medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 electron mc signal barrel WGJets medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJets_new.txt txxx_pdf 2018 electron mc signal endcap WGJets medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 muon mc signal barrel WGJJ medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 muon mc signal endcap WGJJ medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 electron mc signal barrel WGJJ medium
#./make_hist_pdf filelist_dir2/tight_for_analysis_WGJJ.txt txxx_pdf 2018 electron mc signal endcap WGJJ medium
