+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out3/significance_35_condor.sh
arguments    = test_signi2
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out3/significance_outputfile35
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out3/significance_errorfile35
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/sig_out3/significance_myexe35.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
