+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step7_significance/sig_out3/significance_7_condor.sh
arguments    = test_signi1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step7_significance/sig_out3/significance_outputfile7
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step7_significance/sig_out3/significance_errorfile7
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step7_significance/sig_out3/significance_myexe7.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
