+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_photonet_v2/unfold_7_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_photonet_v2/unfold_outputfile7
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_photonet_v2/unfold_errorfile7
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step5_unfold/unfold_photonet_v2/unfold_myexe7.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
