./make_hist filelist_dir/lep.txt $1 2016 data all data data_lepton medium 4 10
./make_hist filelist_dir/lep.txt $1 2016 data all data_fake data_lepton medium 4 10
./make_hist filelist_dir/tight_for_fakephoton_WGJets.txt $1 2016 mc all true WGJets medium 4 10
./make_hist filelist_dir/lep.txt $1 2016 data all data data_lepton medium 4 7
./make_hist filelist_dir/lep.txt $1 2016 data all data_fake data_lepton medium 4 7
./make_hist filelist_dir/tight_for_fakephoton_WGJets.txt $1 2016 mc all true WGJets medium 4 7
./make_hist filelist_dir/lep.txt $1 2016 data all data data_lepton medium 7 10
./make_hist filelist_dir/lep.txt $1 2016 data all data_fake data_lepton medium 7 10
./make_hist filelist_dir/tight_for_fakephoton_WGJets.txt $1 2016 mc all true WGJets medium 7 10
