# muon
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WGJets muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WGJJ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_s muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_t muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tbar muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tbarW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WZ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ZZ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ZG muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal TTG muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WGJets muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WGJJ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_s muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_t muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tbar muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tbarW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WW muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WZ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ZZ muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ZG muon medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control TTG muon medium ptlep
# electron
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WGJets electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WGJJ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_s electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_t electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tbar electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ST_tbarW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal WZ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ZZ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal ZG electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc signal TTG electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WGJets electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WGJJ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_s electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_t electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tbar electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ST_tbarW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WW electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control WZ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ZZ electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control ZG electron medium ptlep
./cal_test 1_out_unfold_1 2_out_ptlep_1 2016 mc control TTG electron medium ptlep
