#signal
hadd hist_dir2/2018_mc_signal_medium_btag_ST_s_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ST_s_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ST_tW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ST_tW_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ST_t_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ST_t_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ST_tbarW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ST_tbarW_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ST_tbar_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ST_tbar_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_TTG_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_TTG_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_WGJJ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_WGJJ_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_WGJets_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_WGJets_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_WW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_WW_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_WZ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_WZ_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ZZ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ZZ_uncertainty.root
hadd hist_dir2/2018_mc_signal_medium_btag_ZG_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_signal_medium_btag_ZG_uncertainty.root
hadd hist_dir2/2018_fakephoton_signal_medium_btag_uncertainty.root test_uncertainty_hist_v2/2018_*_fakephoton_signal_medium_btag_Singl*_uncertainty.root
#control
hadd hist_dir2/2018_mc_control_medium_btag_ST_s_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ST_s_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ST_tW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ST_tW_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ST_t_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ST_t_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ST_tbarW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ST_tbarW_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ST_tbar_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ST_tbar_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_TTG_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_TTG_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_WGJJ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_WGJJ_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_WGJets_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_WGJets_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_WW_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_WW_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_WZ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_WZ_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ZZ_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ZZ_uncertainty.root
hadd hist_dir2/2018_mc_control_medium_btag_ZG_uncertainty.root test_uncertainty_hist_v2/2018_*_mc_control_medium_btag_ZG_uncertainty.root
hadd hist_dir2/2018_fakephoton_control_medium_btag_uncertainty.root test_uncertainty_hist_v2/2018_*_fakephoton_control_medium_btag_Singl*_uncertainty.root
