+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step2_fake_photon/test_sideband/fakephoton_8_condor.sh
arguments    = test_sideband4
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step2_fake_photon/test_sideband/fakephoton_outputfile8
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step2_fake_photon/test_sideband/fakephoton_errorfile8
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step2_fake_photon/test_sideband/fakephoton_myexe8.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
