+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_23_condor.sh
arguments    = test_aqgc1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_outputfile23
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_errorfile23
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_myexe23.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
