+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_4_condor.sh
arguments    = test_aqgc2
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_outputfile4
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_errorfile4
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step4_aqgc/calculate_uncer/step6_uncertainty/aqgc_out1/aqgc_myexe4.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
