./limit_hist filelist_dir/tight_for_analysis_WGJJ.txt 2_out_1 2016 all mc WGJJ medium
./limit_hist filelist_dir/tight_for_analysis_ST_s.txt 2_out_1 2016 all mc ST_s medium
./limit_hist filelist_dir/tight_for_analysis_ST_t.txt 2_out_1 2016 all mc ST_t medium
./limit_hist filelist_dir/tight_for_analysis_ST_tbar.txt 2_out_1 2016 all mc ST_tbar medium
./limit_hist filelist_dir/tight_for_analysis_ST_tW.txt 2_out_1 2016 all mc ST_tW medium
./limit_hist filelist_dir/tight_for_analysis_ST_tbarW.txt 2_out_1 2016 all mc ST_tbarW medium
./limit_hist filelist_dir/tight_for_analysis_TTG.txt 2_out_1 2016 all mc TTG medium
./limit_hist filelist_dir/tight_for_analysis_WW.txt 2_out_1 2016 all mc WW medium
./limit_hist filelist_dir/tight_for_analysis_WZ.txt 2_out_1 2016 all mc WZ medium
./limit_hist filelist_dir/tight_for_analysis_ZZ.txt 2_out_1 2016 all mc ZZ medium
./limit_hist filelist_dir/tight_for_analysis_ZG.txt 2_out_1 2016 all mc ZG medium
./limit_hist filelist_dir/tight_for_analysis_WGJets.txt 2_out_1 2016 all mc WGJets medium
./limit_hist filelist_dir/tight_for_analysis_lepton.txt 2_out_1 2016 all data SingleLepton medium
./limit_hist filelist_dir/tight_for_analysis_lepton.txt 2_out_1 2016 all fakephoton SingleLepton medium
./limit_hist filelist_dir/loose_for_analysis_lepton.txt 2_out_1 2016 all doublefake SingleLepton medium
./limit_hist filelist_dir/loose_for_analysis_lepton.txt 2_out_1 2016 all fakelepton SingleLepton medium
