+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out1/significance_62_condor.sh
arguments    = test_sig6
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out1/significance_outputfile62
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out1/significance_errorfile62
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step7_significance/calculate_uncer/step6_uncertainty/sig_out1/significance_myexe62.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
