+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_ptlep/unfold_42_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_ptlep/unfold_outputfile42
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_ptlep/unfold_errorfile42
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_ptlep/unfold_myexe42.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
