+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out3/fiducial_8_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out3/fiducial_outputfile8
error        = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out3/fiducial_errorfile8
log          = /data/pku/home/pengj/testvbs/analysis/analysis2016/step6_fiducial_xs/fiducial_out3/fiducial_myexe8.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
