+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_117_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_outputfile117
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_errorfile117
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_myexe117.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
