+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_63_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_outputfile63
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_errorfile63
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step6_fiducial_xs/fiducial_out3/fiducial_myexe63.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
