+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_64_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_outputfile64
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_errorfile64
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_myexe64.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
