+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_97_condor.sh
arguments    = test_fiducial1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_outputfile97
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_errorfile97
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step6_fiducial_xs/fiducial_out1/fiducial_myexe97.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
