+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_mla/unfold_100_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_mla/unfold_outputfile100
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_mla/unfold_errorfile100
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_mla/unfold_myexe100.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
