+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2017/step2_fake_photon/test_closure/fakephoton_6_condor.sh
arguments    = test_closure4
output       = /data/pku/home/pengj/testvbs/analysis/analysis2017/step2_fake_photon/test_closure/fakephoton_outputfile6
error        = /data/pku/home/pengj/testvbs/analysis/analysis2017/step2_fake_photon/test_closure/fakephoton_errorfile6
log          = /data/pku/home/pengj/testvbs/analysis/analysis2017/step2_fake_photon/test_closure/fakephoton_myexe6.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
