+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_2_condor.sh
arguments    = test_closure4
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_outputfile2
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_errorfile2
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_myexe2.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
