+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_1_condor.sh
arguments    = test_closure4
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_outputfile1
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_errorfile1
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/test_closure/fakephoton_myexe1.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
