+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfolding_out2/unfolding_106_condor.sh
arguments    = test_unfolding1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfolding_out2/unfolding_outputfile106
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfolding_out2/unfolding_errorfile106
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfolding_out2/unfolding_myexe106.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
