+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_0_condor.sh
arguments    = test_fp_sb
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_outputfile0
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_errorfile0
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_myexe0.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
