+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_7_condor.sh
arguments    = test_fp_sb
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_outputfile7
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_errorfile7
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step2_fake_photon/fp_out/fp_myexe7.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
