+AcctGroup = "pku"
+AcctGroupUser  = "pengj"
executable   = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_photonet/unfold_78_condor.sh
arguments    = test_1
output       = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_photonet/unfold_outputfile78
error        = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_photonet/unfold_errorfile78
log          = /data/pku/home/pengj/testvbs/analysis/analysis2018/step5_unfold/unfold_photonet/unfold_myexe78.log
request_cpus   = 1
request_memory = 1024
request_disk   = 1024
should_transfer_files = yes
queue
